python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 2 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 3 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 4 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 5 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 6 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 7 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 9 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 10 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 11 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 12 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 4 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 2 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 4 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 3 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 4 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 4 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 4 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 5 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 4 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 6 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 4 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 7 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 4 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 4 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 9 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 4 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 10 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 4 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 11 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 4 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode batch --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 12 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 4 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 2048
sleep 1
