python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 1 --seq_length 4096 --pp_deg 1 --global_tp_deg 1 --global_checkpoint 0 --vocab_tp 1
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --seq_length 4096 --pp_deg 1 --global_tp_deg 1 --global_checkpoint 0 --vocab_tp 1
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 1 --seq_length 4096 --pp_deg 1 --global_tp_deg 2 --global_checkpoint 0 --vocab_tp 1
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --seq_length 4096 --pp_deg 1 --global_tp_deg 2 --global_checkpoint 0 --vocab_tp 1
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 1 --seq_length 4096 --pp_deg 1 --global_tp_deg 2 --global_checkpoint 0 --vocab_tp 2
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --seq_length 4096 --pp_deg 1 --global_tp_deg 2 --global_checkpoint 0 --vocab_tp 2
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 1 --seq_length 4096 --pp_deg 1 --global_tp_deg 4 --global_checkpoint 0 --vocab_tp 1
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --seq_length 4096 --pp_deg 1 --global_tp_deg 4 --global_checkpoint 0 --vocab_tp 1
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 1 --seq_length 4096 --pp_deg 1 --global_tp_deg 4 --global_checkpoint 0 --vocab_tp 4
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --seq_length 4096 --pp_deg 1 --global_tp_deg 4 --global_checkpoint 0 --vocab_tp 4
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 1 --seq_length 4096 --pp_deg 1 --global_tp_deg 8 --global_checkpoint 0 --vocab_tp 1
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --seq_length 4096 --pp_deg 1 --global_tp_deg 8 --global_checkpoint 0 --vocab_tp 1
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 1 --seq_length 4096 --pp_deg 1 --global_tp_deg 8 --global_checkpoint 0 --vocab_tp 8
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --seq_length 4096 --pp_deg 1 --global_tp_deg 8 --global_checkpoint 0 --vocab_tp 8
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 1 --seq_length 4096 --pp_deg 1 --global_tp_deg 1 --global_checkpoint 1 --vocab_tp 1
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --seq_length 4096 --pp_deg 1 --global_tp_deg 1 --global_checkpoint 1 --vocab_tp 1
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --seq_length 4096 --pp_deg 2 --global_tp_deg 1 --global_checkpoint 0 --vocab_tp 1
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --seq_length 4096 --pp_deg 2 --global_tp_deg 2 --global_checkpoint 0 --vocab_tp 1
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --seq_length 4096 --pp_deg 2 --global_tp_deg 2 --global_checkpoint 0 --vocab_tp 2
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --seq_length 4096 --pp_deg 2 --global_tp_deg 4 --global_checkpoint 0 --vocab_tp 1
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 2 --seq_length 4096 --pp_deg 2 --global_tp_deg 4 --global_checkpoint 0 --vocab_tp 4
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 4 --seq_length 4096 --pp_deg 4 --global_tp_deg 1 --global_checkpoint 0 --vocab_tp 1
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 4 --seq_length 4096 --pp_deg 4 --global_tp_deg 2 --global_checkpoint 0 --vocab_tp 1
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 8 train_dist_random.py --set_experts_manually 0 --profile_mode static --shape_order SBH --profile_unit all --model_size llama-7b --hidden_size 4096 --num_attention_heads 32 --vocab_size 32000 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 8 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 1 --profile_forward 0 --initialize_on_meta 1 --global_tp_consec 1 --sdp 1 --chunks 1 --pipeline_type gpipe --default_dp_type zero3 --mixed_precision bf16 --shape_order SBH --use-flash-attn  --sequence-parallel  --num_hidden_layers 4 --seq_length 4096 --pp_deg 4 --global_tp_deg 2 --global_checkpoint 0 --vocab_tp 2
sleep 1
